spring:
  application:
    name: "config-client"
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8080
  # DataSource 설정
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: jdbc:mysql://${app.parents-db.host}:${app.parents-db.port}/pudding?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${app.parents-db.username}
    password: ${app.parents-db.password}
server:
  port: 8081
service:
  client:
    text: ${service.text}
management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: INFO
